version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.12.2
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamo-admin:
    image: instructure/dynamo-local-admin
    restart: always
    ports:
      - "5604:8000"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
