# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kv.proto',
  package='kv.proto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08kv.proto\x12\x08kv.proto\"\"\n\x04\x64\x61ta\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"*\n\x0bset_request\x12\x1b\n\x03req\x18\x01 \x02(\x0b\x32\x0e.kv.proto.data\"^\n\x0cset_response\x12-\n\x05\x65rror\x18\x01 \x02(\x0e\x32\x1e.kv.proto.set_response.error_t\"\x1f\n\x07\x65rror_t\x12\x06\n\x02ok\x10\x01\x12\x0c\n\x08internal\x10\x02\"\x1a\n\x0bget_request\x12\x0b\n\x03key\x18\x01 \x02(\t\"\x8a\x01\n\x0cget_response\x12-\n\x05\x65rror\x18\x01 \x02(\x0e\x32\x1e.kv.proto.get_response.error_t\x12\x1b\n\x03req\x18\x02 \x01(\x0b\x32\x0e.kv.proto.data\".\n\x07\x65rror_t\x12\x06\n\x02ok\x10\x01\x12\r\n\tnot_found\x10\x02\x12\x0c\n\x08internal\x10\x03\"\xbb\x02\n\x0creq_envelope\x12-\n\x04type\x18\x01 \x02(\x0e\x32\x1f.kv.proto.req_envelope.msg_type\x12&\n\x07set_req\x18\x02 \x01(\x0b\x32\x15.kv.proto.set_request\x12(\n\x08set_resp\x18\x03 \x01(\x0b\x32\x16.kv.proto.set_response\x12&\n\x07get_req\x18\x04 \x01(\x0b\x32\x15.kv.proto.get_request\x12(\n\x08get_resp\x18\x05 \x01(\x0b\x32\x16.kv.proto.get_response\"X\n\x08msg_type\x12\x11\n\rset_request_t\x10\x01\x12\x12\n\x0eset_response_t\x10\x02\x12\x11\n\rget_request_t\x10\x03\x12\x12\n\x0eget_response_t\x10\x04'
)



_SET_RESPONSE_ERROR_T = _descriptor.EnumDescriptor(
  name='error_t',
  full_name='kv.proto.set_response.error_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ok', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='internal', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=165,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_SET_RESPONSE_ERROR_T)

_GET_RESPONSE_ERROR_T = _descriptor.EnumDescriptor(
  name='error_t',
  full_name='kv.proto.get_response.error_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ok', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='not_found', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='internal', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=319,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_GET_RESPONSE_ERROR_T)

_REQ_ENVELOPE_MSG_TYPE = _descriptor.EnumDescriptor(
  name='msg_type',
  full_name='kv.proto.req_envelope.msg_type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='set_request_t', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='set_response_t', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='get_request_t', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='get_response_t', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=595,
  serialized_end=683,
)
_sym_db.RegisterEnumDescriptor(_REQ_ENVELOPE_MSG_TYPE)


_DATA = _descriptor.Descriptor(
  name='data',
  full_name='kv.proto.data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.proto.data.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.proto.data.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_SET_REQUEST = _descriptor.Descriptor(
  name='set_request',
  full_name='kv.proto.set_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='kv.proto.set_request.req', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=100,
)


_SET_RESPONSE = _descriptor.Descriptor(
  name='set_response',
  full_name='kv.proto.set_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='kv.proto.set_response.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SET_RESPONSE_ERROR_T,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=196,
)


_GET_REQUEST = _descriptor.Descriptor(
  name='get_request',
  full_name='kv.proto.get_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.proto.get_request.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=224,
)


_GET_RESPONSE = _descriptor.Descriptor(
  name='get_response',
  full_name='kv.proto.get_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='kv.proto.get_response.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req', full_name='kv.proto.get_response.req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GET_RESPONSE_ERROR_T,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=365,
)


_REQ_ENVELOPE = _descriptor.Descriptor(
  name='req_envelope',
  full_name='kv.proto.req_envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kv.proto.req_envelope.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_req', full_name='kv.proto.req_envelope.set_req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_resp', full_name='kv.proto.req_envelope.set_resp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_req', full_name='kv.proto.req_envelope.get_req', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_resp', full_name='kv.proto.req_envelope.get_resp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQ_ENVELOPE_MSG_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=683,
)

_SET_REQUEST.fields_by_name['req'].message_type = _DATA
_SET_RESPONSE.fields_by_name['error'].enum_type = _SET_RESPONSE_ERROR_T
_SET_RESPONSE_ERROR_T.containing_type = _SET_RESPONSE
_GET_RESPONSE.fields_by_name['error'].enum_type = _GET_RESPONSE_ERROR_T
_GET_RESPONSE.fields_by_name['req'].message_type = _DATA
_GET_RESPONSE_ERROR_T.containing_type = _GET_RESPONSE
_REQ_ENVELOPE.fields_by_name['type'].enum_type = _REQ_ENVELOPE_MSG_TYPE
_REQ_ENVELOPE.fields_by_name['set_req'].message_type = _SET_REQUEST
_REQ_ENVELOPE.fields_by_name['set_resp'].message_type = _SET_RESPONSE
_REQ_ENVELOPE.fields_by_name['get_req'].message_type = _GET_REQUEST
_REQ_ENVELOPE.fields_by_name['get_resp'].message_type = _GET_RESPONSE
_REQ_ENVELOPE_MSG_TYPE.containing_type = _REQ_ENVELOPE
DESCRIPTOR.message_types_by_name['data'] = _DATA
DESCRIPTOR.message_types_by_name['set_request'] = _SET_REQUEST
DESCRIPTOR.message_types_by_name['set_response'] = _SET_RESPONSE
DESCRIPTOR.message_types_by_name['get_request'] = _GET_REQUEST
DESCRIPTOR.message_types_by_name['get_response'] = _GET_RESPONSE
DESCRIPTOR.message_types_by_name['req_envelope'] = _REQ_ENVELOPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

data = _reflection.GeneratedProtocolMessageType('data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.proto.data)
  })
_sym_db.RegisterMessage(data)

set_request = _reflection.GeneratedProtocolMessageType('set_request', (_message.Message,), {
  'DESCRIPTOR' : _SET_REQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.proto.set_request)
  })
_sym_db.RegisterMessage(set_request)

set_response = _reflection.GeneratedProtocolMessageType('set_response', (_message.Message,), {
  'DESCRIPTOR' : _SET_RESPONSE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.proto.set_response)
  })
_sym_db.RegisterMessage(set_response)

get_request = _reflection.GeneratedProtocolMessageType('get_request', (_message.Message,), {
  'DESCRIPTOR' : _GET_REQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.proto.get_request)
  })
_sym_db.RegisterMessage(get_request)

get_response = _reflection.GeneratedProtocolMessageType('get_response', (_message.Message,), {
  'DESCRIPTOR' : _GET_RESPONSE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.proto.get_response)
  })
_sym_db.RegisterMessage(get_response)

req_envelope = _reflection.GeneratedProtocolMessageType('req_envelope', (_message.Message,), {
  'DESCRIPTOR' : _REQ_ENVELOPE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.proto.req_envelope)
  })
_sym_db.RegisterMessage(req_envelope)


# @@protoc_insertion_point(module_scope)
